<?php
return array (
  'app' => 'Admin',
  'model' => 'WeixinPublic',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '0',
  'name' => '微信管理',
  'icon' => 'weixin',
  'remark' => '',
  'listorder' => '50',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'WeixinPublic',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '公众号管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Weixin',
      'action' => 'welcome',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '欢迎语',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Weixin',
      'action' => 'menu',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '自定义菜单',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    array (
      'app' => 'Admin',
      'model' => 'WeixinBroads',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '定时群发',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
    array (
      'app' => 'Admin',
      'model' => 'WeixinReply',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '自动回复',
      'icon' => '',
      'remark' => '',
      'listorder' => '4',
    ),
  ),
);