<?php
return array (
  'app' => 'Admin',
  'model' => 'Article',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '1',
  'name' => '文章管理',
  'icon' => '',
  'remark' => '',
  'listorder' => '29',
  'children' => 
  array (
    array (
      'app' => 'Portal',
      'model' => 'AdminPost',
      'action' => 'article',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '文章列表',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminPost',
      'action' => 'comment_article',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '评论管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '1',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminPost',
      'action' => 'recyarticle',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '文章回收',
      'icon' => '',
      'remark' => '',
      'listorder' => '2',
    ),
    array (
      'app' => 'Portal',
      'model' => 'AdminTerm',
      'action' => 'index_article',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '分类管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '3',
    ),
  ),
);