<?php
return array (
  'app' => 'Admin',
  'model' => 'Information',
  'action' => 'default',
  'data' => '',
  'type' => '1',
  'status' => '0',
  'name' => '板块管理',
  'icon' => 'cogs',
  'remark' => '',
  'listorder' => '0',
  'children' => 
  array (
    array (
      'app' => 'Admin',
      'model' => 'Information',
      'action' => 'circle_list',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '专题',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Information',
      'action' => 'index',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '帖子管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Information',
      'action' => 'post_reply',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '帖子评论管理',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
    array (
      'app' => 'Admin',
      'model' => 'Information',
      'action' => 'circle_type',
      'data' => '',
      'type' => '1',
      'status' => '1',
      'name' => '板块类型',
      'icon' => '',
      'remark' => '',
      'listorder' => '0',
    ),
  ),
);